-- V2: Create categories table
CREATE TABLE tb_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    parent_category_id BIGINT,
    CONSTRAINT fk_categories_parent FOREIGN KEY (parent_category_id) REFERENCES tb_categories(id)
);

CREATE INDEX idx_categories_parent ON tb_categories(parent_category_id);