-- V3: Create products table
CREATE TABLE tb_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    price DECIMAL(10, 2) NOT NULL,
    sku VARCHAR(50) NOT NULL UNIQUE,
    stock_quantity INTEGER NOT NULL,
    category_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES tb_categories(id)
);

CREATE INDEX idx_products_sku ON tb_products(sku);
CREATE INDEX idx_products_category ON tb_products(category_id);