-- V4: Create orders table
CREATE TABLE tb_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_amount DECIMAL(10, 2) NOT NULL,
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES tb_users(id)
);

CREATE INDEX idx_orders_user ON tb_orders(user_id);
CREATE INDEX idx_orders_status ON tb_orders(status);
CREATE INDEX idx_orders_created ON tb_orders(created_at);