-- V5: Create order_items table
CREATE TABLE tb_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price DECIMAL(10, 2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES tb_orders(id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES tb_products(id)
);

CREATE INDEX idx_order_items_order ON tb_order_items(order_id);
CREATE INDEX idx_order_items_product ON tb_order_items(product_id);