-- V6: Create payments table
CREATE TABLE tb_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE,
    payment_method VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES tb_orders(id)
);

CREATE INDEX idx_payments_order ON tb_payments(order_id);
CREATE INDEX idx_payments_status ON tb_payments(status);